#!/bin/sh

############################################################################
#
# This script is similar to nightly.sh, except that it regenerates the history
# file first. It also puts the output into a different directory and cleans up
# after itself, making sure not to overwrite anything in use. This is useful
# for seeing how changes to a script will affect the output.
#
# Author: Mark Tengi <markat@princeton.edu>
#
# Script written for election.princeton.edu run by Samuel S.-H. Wang under
# noncommercial-use-only license:
# You may use or modify this software, but only for noncommericial purposes.
# To seek a commercial-use license, contact sswang@princeton.edu
#
############################################################################

exit # This isn't ready yet. Don't run it

HISTORY=Senate_estimate_history.csv

cd /web/python/
./update_polls.py
cd ..

cp -f python/2014.Senate.polls.median.txt matlab/

# Regenerate history
./bin/regenerate-history.sh

cd /web/matlab/
# Trim off the last line of Senate_estimate_history.csv, as it will be
# regenerated by Senate_runner1
mv $HISTORY SEH.tmp
head -n -1 SEH.tmp > $HISTORY
rm -f SEH.tmp

# Make all of the graphics with Xvfb so that they'll look nice
XVFB_DISPLAY=99
Xvfb :$XVFB_DISPLAY -screen 0 1280x1024x24 &
XVFB_PID=$!
export DISPLAY=:$XVFB_DISPLAY
matlab -r Senate_runner1
matlab -r Senate_runner2
kill $XVFB_PID
cd ..

cd python/
./current_senate.py
./jerseyvotes.py
cd ..

mv -f python/*.html output2/
mv -f python/*.txt output2/

mv -f matlab/*.jpg output2/
mv -f matlab/*.csv output2/

# Reinstate history file backed up by regenerate-history.sh, 
mv matlab/Senate_estimate_history.csv.old matlab/Senate_estimate_history.csv
